package ec.edu.ucuenca.prueba;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Persona implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "PERSONA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "PERSONA_ID_GENERATOR", sequenceName = "PERSONA_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Nombre")
   private java.lang.String nombre;

   @org.kie.api.definition.type.Label(value = "Direccion")
   private java.lang.String direccion;

   public Persona()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.String getDireccion()
   {
      return this.direccion;
   }

   public void setDireccion(java.lang.String direccion)
   {
      this.direccion = direccion;
   }

   public Persona(java.lang.Long id, java.lang.String nombre,
         java.lang.String direccion)
   {
      this.id = id;
      this.nombre = nombre;
      this.direccion = direccion;
   }

}